/* This file is in ISO8859-1 encoding */
static Ihandle* iup_load_lng_portuguese_matrix (void)
{
  return IupSetAtt( "PORTUGUESE", IupUser(), 
    "IUP_ALLLINES", "Todas as Linhas", 
    "IUP_ASCENDING", "Ascendente", 
    "IUP_BY_COL", "por Colunas", 
    "IUP_BY_ROW", "por Linhas", 
    "IUP_CASESENSITIVE", "Diferenciar maiúsculas e minúsculas", 
    "IUP_CLEARVALUE", "Limpar Valores", 
    "IUP_CLOSE", "Fechar", 
    "IUP_COLUMN", "Coluna", 
    "IUP_COLUMNDECIMALS", "Decimais da Coluna", 
    "IUP_COLUMNDECIMALSDLG", "Decimais da Coluna...", 
    "IUP_COLUMNUNITS", "Unidades da Coluna", 
    "IUP_COLUMNUNITSDLG", "Unidades da Coluna...", 
    "IUP_COPYAC", "Copiar	Ctrl+C", 
    "IUP_COPYCOLTO_ALL", "Copiar para Todas as Linhas", 
    "IUP_COPYCOLTO_BOTTOM", "Copiar para fim", 
    "IUP_COPYCOLTO_INTERVAL", "Copiar para Intervalo", 
    "IUP_COPYCOLTO_MARKED", "Copiar para Selecionadas", 
    "IUP_COPYCOLTO_TOP", "Copiar para Topo", 
    "IUP_COPYTOINTERVAL", "Copiar Para - Intervalo", 
    "IUP_COPYTOSAMECOLUMN", "Copiar Para (Mesma Coluna)", 
    "IUP_CURRENTSTATE", "Estado Corrente", 
    "IUP_CUTAC", "Recortar	Ctrl+X", 
    "IUP_DECIMALS", "Decimais:", 
    "IUP_DECIMALSYMBOL", "Símbolo Decimal:", 
    "IUP_DESCENDING", "Descendente", 
    "IUP_EDITCELL", "Editar Célula", 
    "IUP_ERASEAC", "Apagar	Del", 
    "IUP_ERRORINVALIDDATA", "Dado inválido.", 
    "IUP_ERRORINVALIDFORMULA", "Fórmula Inválida.", 
    "IUP_ERRORINVALIDINTERVAL", "Intervalo inválido.", 
    "IUP_ERRORINVALIDSELECTION", "Seleção inválida.", 
    "IUP_ERRORNOSELECTION", "Seleção vazia.", 
    "IUP_ERRORNOTEXT", "Texto vazio.", 
    "IUP_EXPORT", "Exportar", 
    "IUP_FIND", "Localizar", 
    "IUP_FINDDLG", "Localizar...	Ctrl+L", 
    "IUP_FIND_NEXT", "Localizar &Próximo", 
    "IUP_FIND_PREVIOUS", "Localizar &Anterior", 
    "IUP_FIND_WHAT", "Localizar o que:", 
    "IUP_FIRSTLINE", "Primeira Linha", 
    "IUP_FOUND_AT", "Encontrado em", 
    "IUP_FREEZE", "Congelar", 
    "IUP_GOTO", "Ir Para", 
    "IUP_GOTODLG", "Ir Para...	Ctrl+G", 
    "IUP_HERETOBOTTOM", "Daqui para o fim", 
    "IUP_HERETOTOP", "Daqui para o topo", 
    "IUP_HIDECOLUMN", "Esconder Coluna", 
    "IUP_HIDELINE", "Esconder Linha", 
    "IUP_IMPORT", "Importar", 
    "IUP_INTERVALDLG", "Intervalo...", 
    "IUP_INVERT", "Inverter", 
    "IUP_INVERT_TIP", "Apenas inverte a ordenação corrente. Novos parâmetros são ignorados.", 
    "IUP_LASTLINE", "Última Linha", 
    "IUP_LINE", "Linha:", 
    "IUP_LINEEND", "Linha Final:", 
    "IUP_LINESTART", "Linha Inicial:", 
    "IUP_MATCH_CASE", "Diferenciar maiúsculas e minúsculas", 
    "IUP_MATCH_WHOLE_CELL", "Coindidir célula inteira", 
    "IUP_NOT_FOUND", "Não encontrado.", 
    "IUP_ORDER", "Ordem", 
    "IUP_OTHERTEXTSEPARATOR", "  - Outro Sep. de Num.:", 
    "IUP_PASTEAC", "Colar	Ctrl+V", 
    "IUP_PASTECLIP", "Colar do Clipboard", 
    "IUP_PASTEDATA", "Colar de um Buffer", 
    "IUP_PASTEFILE", "Colar de Arquivo (Importar)", 
    "IUP_REDOAC", "Refazer	Ctrl+R", 
    "IUP_REDONAME", "Refazer", 
    "IUP_SEARCH", "Pesquisar", 
    "IUP_SELECTALLAC", "Selecionar Tudo	Ctrl+T", 
    "IUP_SELECTEDLINES", "Linhas Selecionadas", 
    "IUP_SETCELL", "Modificar Célula", 
    "IUP_SETTINGSDLG", "Definições...", 
    "IUP_SHOWHIDDENCOLUMNS", "Mostrar Coluna Escondidas", 
    "IUP_SHOWHIDDENLINES", "Mostrar Linhas Escondidas", 
    "IUP_SORT", "Ordenar", 
    "IUP_SORTBYCOLUMN", "Classificar Linhas por Coluna", 
    "IUP_SORTDLG", "Classificar...", 
    "IUP_TEXTSEPARATOR", "Separador de Números:", 
    "IUP_UNDOAC", "Desfazer	Ctrl+Z", 
    "IUP_UNDOLIST", "Lista de Desfazer", 
    "IUP_UNDOLISTDLG", "Lista de Desfazer...	Ctrl+U", 
    "IUP_UNDONAME", "Desfazer", 
    "IUP_UNFREEZE", "Descongelar", 
    "IUP_UNITS", "Unidades:", 
    "IUP_VISIBILITY", "Visibilidade", NULL );
}
